---
deployment:
  tasks:
    - export PHP_PATH=/opt/cpanel/ea-php72/root/usr/bin/php
    - export DEPLOY_PATH=/home/NOMEDOMINIO/public_html
    - /bin/wget 'https://getcomposer.org/installer' -O composer-installer.php
    - /bin/cp ./.env.production ./.env
    - $PHP_PATH -d allow_url_fopen=on composer-installer.php
    - $PHP_PATH composer.phar install --optimize-autoloader --no-dev
    - /bin/rm -f ./composer.phar
    - /bin/rm -f ./composer-installer.php
    - /bin/cp -r * $DEPLOY_PATH
    - /bin/cp  ./.env $DEPLOY_PATH/
    - /bin/cp ./.htaccess $DEPLOY_PATH/
    - /bin/bash ./deploy.sh $DEPLOY_PATH
    