---
deployment:
  tasks:
    - export NPM_PATH=/opt/cpanel/ea-nodejs10/bin/npm
    - export DIST_PATH=fuse
    - export DEPLOY_PATH=/home/intranet/public_html
    - $NPM_PATH install --scripts-prepend-node-path
    - $NPM_PATH run build --prod --scripts-prepend-node-path
    - /bin/mkdir -p $DEPLOY_PATH
    - /bin/cp -r ./dist/$DIST_PATH/* $DEPLOY_PATH